@baseUrl=http://localhost:3200/api

@resourceName=categories

# @name getAllCategories
Get {{baseUrl}}/{{resourceName}}

###
# @name fillterCategoriesByIdSubCategory
Get {{baseUrl}}/{{resourceName}}?idSubCategory=3ac6848a-c7d7-432c-85cf-83c21d6022ad

###
# @name fillterProductsByCategoryId
Get {{baseUrl}}/{{resourceName}}?id=71cd4b24-c868-4800-9305-08d77857535c

###
# @name pagination
Get {{baseUrl}}/{{resourceName}}?_page=1&_limit=2

###
# @name addNewCategory
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "idSubCategory": "2",
    "name": "Kids 1",
    "status": 1,
  }

###
# @name updateCategory
PATCH {{baseUrl}}/{{resourceName}}/qHB5jNw
Content-Type: application/json

{
  "idSubCategory": "2",
  "name": "Kids 1",
  "status": 2,
  "createdAt": 1624964110216
}

###
# @name deleteCategory
DELETE  {{baseUrl}}/{{resourceName}}/qHB5jNw
