@baseUrl=http://localhost:3200/api

@resourceName=paymentMethod

# @name getAllPaymentMethod
Get {{baseUrl}}/{{resourceName}}

###
# @name fillterPaymentMethodById
Get {{baseUrl}}/{{resourceName}}?id=5d1b8222-8241-45dd-ac89-70d1793b6f4b

###
# @name pagination
Get {{baseUrl}}/{{resourceName}}?_page=1&_limit=2

###
# @name addNewPaymentMethod
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
      "name": "Gửi hàng qua bưu điện",
      "fee": 10000
    }

###
# @name updatePaymentMethod
PATCH {{baseUrl}}/{{resourceName}}/fJSJ8n7
Content-Type: application/json

{
  "isShow": 1624964110216
}

###
# @name deletePaymentMethod
DELETE  {{baseUrl}}/{{resourceName}}/fJSJ8n7
